name: CyberionPOI
main: com.poke.cyberion.poi.CyberionPlugin
version: 1.0
api-version: 1.16
author: The_Poke
depend:
commands:
  POI:
      description: Main command for Cyberion POI
      usage: /POI [set, remove, list, reload, book]
  discord:
      description: Show discord link
      usage: /discord

